config/routes.rb
OrderApp::Application.routes.draw do
  
  get "order_tickets/new"
  get "order_tickets/create"
  get "order_tickets/index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :stores, only: [:edit, :update, :show] 
  resources :users, except: [:new, :show, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: :create
  resources :store_sessions, only: :create
  resources :meal_limits, only: [:create, :destroy]
  resources :orders, only: [:new, :create, :show]
  resources :password_recovery
  
  root 'static_pages#home'
  
  match '/signup',  to: 'users#new',  via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/store/signin', to: 'store_sessions#new', via: 'get'
  match '/store/signout', to: 'store_sessions#destroy', via: 'delete'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/view_stores', to: 'static_pages#stores_index', via: 'get'
  match '/close_stores', to: 'static_pages#close_store_list', via: 'get'

  match '/store/meal_index', to: 'meal_limits#index', via: 'get'

  match '/past_meals', to: 'meals#index', via: 'get'
  match '/meal/:id', to: 'meals#show', via: 'get', as: 'meal'
  match '/order_history/:id', to: 'meals#order_history', via: 'get', as: 'order_history'

  match '/store/meal/:id', to: 'meal_limits#show', via: 'get', as: 'select_meal'

  match '/store/current_orders', to: 'store_orders#todays_orders', via: 'get'
  match '/store/ready_for_pickup', to: 'store_orders#ready_for_pickup', via: 'patch'
  match '/store/pickup_list', to: 'store_orders#pickup_list', via: 'get'
  match '/store/past_orders', to: 'store_orders#past_orders', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

attr_accessor :active, :past, :my_current_store  

  def home
    @meals_active = Meal.active
    @meal_active = @meals_active.first
    @meals_past = Meal.past
    @meal_past = @meals_past.order("date DESC").first
    
    unless @meal_active.nil?
   
    @meal_photos = @meal_active.meal_photos
    @meal = Meal.find_by_id(@meal_active.id)
    
    else

    @meal_photos = @meal_past.meal_photos
    @meal = Meal.find_by_id(@meal_past)
    end
    
    if user_signed_in?
    @my_stores = current_user.relationships
    end

    if @meal_active.present? && @my_stores.present?
    @store = Store.find_by_id(current_user.relationships.my_current_store.store_id)
    @store_meal = MealLimit.find_by_store_id_and_meal_id(@store.id, @meal_active.id)
    @meals_available = MealLimit.meal_available
    @meal_available = @store_meal && @meals_available
    end

    if current_store.present? && @meal_active.present?
    @order_count = Order.where(meal_id: @meal_active.id).where(store_id: current_store.id).count
    end
   end

  def close_store_list
    @close_stores = current_user.stores_nearby
    @user_zip = current_user.user_location
    

    @meals_active = Meal.active
    @meal_active = @meals_active.first

    @meals_available = MealLimit.meal_available 

    respond_to do |format|
      format.html
      format.js 
    end
  end

  def stores_index
    @meals_active = Meal.active
    @meal_active = @meals_active.first

    if user_signed_in?
    @my_stores = current_user.relationships
    end

    if @meal_active.present? && @my_stores.present?
    @store = Store.find_by_id(current_user.relationships.current_store.store_id)
    @store_meal = MealLimit.find_by_store_id_and_meal_id(@store.id, @meal_active.id)
    @meals_available = MealLimit.meal_available
    @meal_available = @store_meal && @meals_available
    end

    if user_signed_in? && (params[:search_zip].nil? || params[:search_zip].empty?)
    @zip_code = current_user.zip.to_s.to_latlon
    @my_stores = current_user.relationships

    elsif user_signed_in? && params[:search_zip].present?
    @zip_code = params[:search_zip].to_s.to_latlon
    @my_stores = current_user.relationships
    
    elsif user_not_signed_in? && params[:search_zip].present?
    @zip_code = params[:search_zip].to_s.to_latlon
    
    else

    @zip_code = 27613.to_s.to_latlon

    end

    @stores = Store.all
    @stores.to_json
  end

  def about
  end

  def contact
  end

  def help
  end

  def privacy
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_chef_layout.html.erb
<div class="row">
	<div class="col-lg-6 text-center">
      	<div class="thumbnail" id="chef_info">
      			<%= image_tag meal_chef(@meal).bio_photo.url %>
      		<div class="caption">
        		<h4><%= meal_chef(@meal).name %></h4>
        		<p id="click_info" style="color: grey"> click to open details </p>
      		</div>
      	</div>
	</div>
</div>


<div class="row">
	<div id="chef_details" class="col-lg-6" style="display: none">
		<h3 class="text-center"><%= (meal_chef(@meal)).restaurants.first.name %></h3>
		<p id="close_chef_details" class="text-center" style="border: 1px solid grey">close</p>
	</div>
</div>

app/views/static_pages/_close_store_list.html.erb
<div class="col-lg-3"></div>
  
  <div class="modal-content col-lg-6">
    <div class="modal-dialog">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">stores nearby</h4>
        </div>

        <div class="modal-body">
          <% if @close_stores.any? %> 
          <ul class= "list-group">
            <% @close_stores.each do |store| %> 

<% if @meal_active.present? %>
<% @store_meal = store.meal_limits.find_by_meal_id(@meal_active.id) %>
<% @meal_available = @store_meal && @meals_available %>
<% end %>


              <li class="list-group-item">
                <h3><%= store.name.downcase %>    <span style="font-size:.75em; color: #AE9494"><%= store.street.downcase %> | <%= store.city.downcase %> <%=store.state.downcase%> <%=store.zip%></span></h3>
                
                <% if current_user.relationships.my_current_store.blank? %>
                  
                  <%= bootstrap_form_for(current_user.relationships.build(store_id: store.id), remote: true) do |f| %> 
                  <div><%= f.hidden_field :store_id %></div>
                  <%= f.submit "Make my store", class: "btn btn-sm btn-success" %>
                  <% end %>

                  <%= render 'static_pages/meal_status_partial' %>

                <% else %>
                  
                    <% if current_user.relationships.my_current_store.store_id == store.id  %>
                          <p>This is your store</p>

                          <%= render 'static_pages/meal_status_partial' %>
                   
                    <% else %>

                          <%= bootstrap_form_for(current_user.relationships.build(store_id: store.id), remote: true) do |f| %> 
                          <div><%= f.hidden_field :store_id %></div>
                          <%= f.submit "Make my store", class: "btn btn-sm btn-success" %>
                          <% end %>

                          <%= render 'static_pages/meal_status_partial' %>

                    <% end %>

                <% end %> 
              </li>
            <% end %>
          </ul>
        <% else %>
          <h2>sorry, there are no close stores here. would you like to look at the map?</h2>
        <% end %>

        </div>

        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
    </div>
  </div>

<div class="col-lg-3"></div>

app/views/static_pages/_map.html.erb
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjxPoPR8K1DEijYx8NOxOEatfbK4hn9DU&sensor=false"
  type="text/javascript"></script>

<script type="text/javascript"> 
function initialize() {
  
  var myLatlng = new google.maps.LatLng(<%= @zip_code %>);
  var mapOptions = {
    zoom: 10,
    center: myLatlng
  }
  var styleArray = [
  {
    featureType: "all",
    stylers: [
      { saturation: -80 }
    ]
  },{
    featureType: "road.arterial",
    elementType: "geometry",
    stylers: [
      { hue: "#00ffee" },
      { saturation: 50 }
    ]
  },{
    featureType: "poi.business",
    elementType: "labels",
    stylers: [
      { visibility: "off" }
    ]
  }
];
  var map = new google.maps.Map(document.getElementById('map-canvas'), mapOptions);
  map.setOptions({styles: styleArray});
  setMarkers(map, stores);
}
  var stores = [<% @stores.each do |x| %>
        [<%= x.latitude %> , <%= x.longitude %>, "<%= x.name %>", "<%= x.street %>", <%= x.id %>], 
        <% end %>
  ];
  function setMarkers (map, locations) {
  for (i = 0; i < locations.length; i++) {  
        var store = locations[i];
        var myLatLng = new google.maps.LatLng(store[0], store[1]);
        var marker = new google.maps.Marker({
        position: myLatLng,
        icon: {
      path: google.maps.SymbolPath.BACKWARD_CLOSED_ARROW,
      scale: 5, 
      hue: "#00ffee"
    },
        map: map, 
        title: store[2], 
      });
        marker.hello = new google.maps.InfoWindow({
          content: '<a data-remote="true" data-target="#store-modal" data-toggle="modal" href="/stores/' + store[4] +'">' + store[2] + '</a>'
      });
        google.maps.event.addListener(marker, 'click', function() {
            this.hello.open(map, this);
      });
  } 
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="map-canvas"></div>

app/views/static_pages/_marquee_meal_partial.html.erb
	<div class="row">
		<h1 class="text-center"><%= @meal.name%></h1>
	</div>

	<div class="row"></div>

	<div class="row">
		<%= render 'static_pages/meal_carousel' %>
	</div>	

	<div class="row">
		<div class="col-lg-9"><%= render 'static_pages/meal_layout' %></div>
		<div class="col-lg-3 my_store_partial"><%= render 'static_pages/store_partial' %></div>
	</div>

	<div class="row">
		<div class="buffer"></div>
	</div>

	<div class="row">
		<div><%= render 'static_pages/chef_layout' %></div>
		<div><%= render 'static_pages/cooking_tools' %></div>
	</div>

app/views/static_pages/_meal_carousel.html.erb
<div id="carousel-active_meal" class="carousel" data-ride="carousel" >
  
  <ol class="carousel-indicators">
    <li data-target="#carousel-active_meal" data-slide-to="0" class="active"></li>
    
    <% @meal_photos.each_with_index do |photo, index| %>
    <li data-target="#carousel-active_meal" data-slide-to=<%= index + 1 %>></li>
    <% end %>
  </ol>

  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag @meal.header_photo.picture.url %>
      <div class="carousel-caption">
        <h3><%= @meal.header_photo.name %>
      </div>
    </div>
  
  <% @meal_photos.each do |photo| %>
    <div class="item">
      <%= image_tag photo.picture.url %>
      <div class="carousel-caption">
      <h3><%= photo.name %> </h3>
      </div>
    </div>
  <% end %>
  </div>

  <a class="left carousel-control" href="#carousel-active_meal" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-active_meal" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>

<script>
$('.carousel').carousel({
    pause: true,
    interval: false
});
</script>

app/views/static_pages/_meal_layout.html.erb
<div class="tab-border">
	<ul class="nav nav-tabs">
		<% @meal.order_options.each do |option| %>
		<li><a href="#<%=option.size%>" data-toggle="tab"><%= option.size %> | $<%= option.price %></a>
		<% end %>
		</li>  
	</ul>


	<div class="tab-content">
		<% @meal.order_options.each do |option| %>
			<div class="tab-pane" id="<%= option.size %>">
			<h3> prep. time: <%=@meal.prep_time %> | cook time: <%= @meal.cook_time %></h3>

		</br>

			<h3> <%= option.feeds %> meals @ $<%= (option.price.to_f / option.feeds.to_f).round(2) %> per meal </h3>	
					<table class="table">
						  <tr>	
							<th>ingredient</th>
							<th>quantity | measurement</th>
						  </tr>

				<% option.ingredients.each do |ingredient| %>		  

						  <tr>
						  	<td><%= ingredient.name %></td>
						  	<td><%=	ingredient.measurement_quantity %> | <%= ingredient.measurement_type %> </td>
						  </tr>
					<% end %>
					</table>
				
				<ol>
					<% option.instructions.each do |instruction| %>
						<li><%= instruction.content %></li>
					<% end %>
				</ol>
				
			<% if @meal_active.present? %>

				<% if current_user.relationships.current_store.present? %>

					<%= form_for(current_user.orders.build(meal_id: @meal.id, store_id: my_store(current_user).id, order_option_id: option.id)) do |f| %>
					<%= f.hidden_field :meal_id %>
					<%= f.hidden_field :store_id %>
					<%= f.hidden_field :order_option_id %>
					

					<h4>$<%=option.price%>

					<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
			          src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    					data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    					data-name="MEALS"
    					data-description="<%= @meal.name %> ($<%= option.price %>)"
    					data-amount="<%= stripe_price(option) %>"
    					data-email="<%= current_user.email %>"
    					data-label="PURCHASE FROM <%=my_store(current_user).name%>">
			        </script>

					<% end %>   

					 <div id="getting-started"></div>

				<% else %>

					<%= link_to "pick a store if you would like to purchase", close_stores_path, class: "btn btn-primary btn-sm", data: {:toggle => "modal", :target => "#store-modal-window", :remote => true} %> 

				<% end %>

			<% else %>

				<p>past meal, can't order </p>

			<% end %>
			</div>
		<% end %>
	</div>
</div>

<script>
$(window).load(function () {
        $('.nav-tabs a:first').tab('show');
    });
$("#getting-started")
   .countdown("<%= @meal.end_time.strftime('%Y/%m/%d %H:%M') %>", function(event) {
      $(this).text(
   event.strftime('%H:%M:%S to order while supplies still available')
  );
});
</script>

app/views/static_pages/_meal_status_partial.html.erb
<% if @meal_active.nil? %>
	<p> no meals are running </p>
<% elsif @meal_available.nil? %>
	<p> store not serving </p>
<% else %>
	<p> you can order </p>
<% end %>

app/views/static_pages/_store_partial.html.erb
   <% unless current_user.relationships.blank? %>       
      <div class="well">
        <h4>your current store is...</h4>
        <p><%= my_store(current_user).name %></p>
        <p><%= my_store(current_user).street %></p>
        <p><%= my_store(current_user).city%> <%= my_store(current_user).state.upcase %> <%= my_store(current_user).zip %></p>
        
        <% unless current_page?(controller: 'static_pages', action: 'stores_index') %> 

        <div>
            <%= link_to 'change', close_stores_url, class: "btn btn-primary btn-sm", data: {:toggle => "modal", :target => "#store-modal-window", :remote => true} %>
        </div>

        <% else %>

         <h3> click the map to pick a store </h3>

        <% end %>

          <% if @meal_active.nil? %>
            <p> no meals are running </p>
          <% elsif @meal_available.nil? %>
            <p> store not serving </p>
          <% else %>
            <p> you can order </p>
          <% end %>


      </div>  
	
  <% else %>
  	  <% unless current_page?(controller: 'static_pages', action: 'stores_index') %> 

       <%= link_to 'find stores nearby', close_stores_url, class: "btn btn-primary btn-lg", data: {:toggle => "modal", :target => "#store-modal-window", :remote => true} %>

      <% else %>

     <h3> click the map to pick a store </h3>
     

      <% end %>
	<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'about') %>

<div class="buffer"></div>

<div class="row">
  <h1 class="text-center">about</h1>
</div>

<div class="buffer"></div>

<div class="row">
  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("email.ico") %>
      <div class="caption">
        <h3>Email</h3>
        <p>You receive an email for a chef designed gormet meal prepared that day</p>
      </div>
    </div>
  </div>

  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("search.ico") %>
      <div class="caption">
        <h3>Search Availability</h3>
        <p>Choose a nearby grocery store to preportion the ingredients for you</p>
      </div>
    </div>
  </div>


  <div class="col-sm-6 col-md-4">
    <div class="thumbnail">
      <%= image_tag("buy.jpg") %>
      <div class="caption">
        <h3>Place Order</h3>
        <p>Order the preportioned meal by 1:00pm that day</p>
      </div>
    </div>
  </div>
</div>

<div class="buffer"></div>

<div class="row">

  <div class="col-md-2"></div>  

    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
       <%= image_tag("car.jpg") %>
        <div class="caption">
          <h3>Pick-up</h3>
          <p>Pick up the preportioned meal anytime after 4:00pm</p>
        </div>
      </div>
    </div>


    <div class="col-sm-6 col-md-4">
      <div class="thumbnail">
       <%= image_tag("eat.jpg") %>
        <div class="caption">
          <h3>Eat!</h3>
          <p>Eat your stress-free and delicious, home-cooked dinner</p>
        </div>
      </div>
    </div>

  <div class="col-md-2"></div>  

</div>

app/views/static_pages/close_store_list.js.erb
$("#store-modal-window").html('<%= j render("static_pages/close_store_list") %>');

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<!-- User signed in -->
<% if user_signed_in? %>

<% provide(:title, current_user.name.downcase) %>

<div class="row">
	<%= render 'static_pages/marquee_meal_partial' %>
</div>    

<!-- ++ Store signed in ++ -->
<% elsif store_signed_in? %>

<% provide(:title, current_store.name) %>

<h1><%= current_store.name %></h1>

<div class="row buffer"></div>

		<!-- Store signed in and meal is running -->
	<% if @meal_active.present? %>
		<div class="row text-center">
			<h1><%= @meal_active.name %></h1>
			<h3>number of orders: <%= @order_count %></h3>
		</div>

		<div class="row buffer"></div>

		<div class="row text-center">
			<%= link_to "Check your current orders", store_current_orders_path, class: "btn btn-large btn-primary"%>
		</div>

		<!-- Store signed in and NO meal running -->
	<% else %>

		<div class="row text-centered">
			<%= link_to "Set Upcoming Meals", store_meal_index_path, id: "sign_up_link", class: "btn btn-large btn-primary"%>
		</div>

	<% end %>

<!-- Neither store nor user is signed in -->
<% else %>

<% provide(:title, 'home') %>

<div class="row">
	<div class="jumbotron">
	    <h1> Welcome to SCARBOROUGH FAIR</h1>
	    <h4> delicious dinners done conveniently </h4>
	</div>
</div>

<div class="row">
	<div class="col-xs-12">
		<%= link_to "Sign up now!", signup_path, id: "sign_up_link", class: "btn btn-large btn-primary", remote: true %>
	</div>
</div>

<% end %>

<div id="store-modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>   

app/views/static_pages/privacy.html.erb
<h1>StaticPages#privacy</h1>
<p>Find me in app/views/static_pages/privacy.html.erb</p>

app/views/static_pages/stores_index.html.erb
<% provide(:title, 'stores') %>


<div class="row">
	<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h1 class="text-center">all participating stores</h1>
		</div>
	<div class="col-lg-3"></div>
</div>

<div class="buffer"></div>

<div class="row">
	<div class="col-lg-3"></div>
		<div class="col-lg-6">
			<h3 class="text-center">
			<%= bootstrap_form_tag url: '/view_stores', method: :get, id: "search-form" do %>
  			<%= text_field_tag :search_zip, params[:search_zip], placeholder: "Search By Zip" %>
  			<%= submit_tag "Search", :name => nil %>
  			<% end %>
  			</h3>
		</div>
	<div class="col-lg-3"></div>
</div>


<% if user_signed_in? %>

<div class="row">
	<div class="col-xs-9"><%= render 'static_pages/map' %></div>
	<div class="col-xs-3"><%= render 'static_pages/store_partial' %></div>
</div>

<% else %>

<div class="row">
	<div class="col-xs-2"></div>
	<div class="col-xs-8"><%= render 'static_pages/map' %></div>
	<div class="col-xs-2"></div>
</div>

<% end %>


<div id="store-modal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>