config/routes.rb
OrderApp::Application.routes.draw do
  
  get "order_tickets/new"
  get "order_tickets/create"
  get "order_tickets/index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :stores, only: [:edit, :update, :show] 
  resources :users, except: [:new, :show, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: :create
  resources :store_sessions, only: :create
  resources :meal_limits, only: [:create, :destroy]
  resources :orders, only: [:new, :create, :show]
  resources :password_recovery
  
  root 'static_pages#home'
  
  match '/signup',  to: 'users#new',  via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/store/signin', to: 'store_sessions#new', via: 'get'
  match '/store/signout', to: 'store_sessions#destroy', via: 'delete'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/view_stores', to: 'static_pages#stores_index', via: 'get'
  match '/close_stores', to: 'static_pages#close_store_list', via: 'get'

  match '/store/meal_index', to: 'meal_limits#index', via: 'get'

  match '/past_meals', to: 'meals#index', via: 'get'
  match '/meal/:id', to: 'meals#show', via: 'get', as: 'meal'
  match '/order_history/:id', to: 'meals#order_history', via: 'get', as: 'order_history'

  match '/store/meal/:id', to: 'meal_limits#show', via: 'get', as: 'select_meal'

  match '/store/current_orders', to: 'store_orders#todays_orders', via: 'get'
  match '/store/ready_for_pickup', to: 'store_orders#ready_for_pickup', via: 'patch'
  match '/store/pickup_list', to: 'store_orders#pickup_list', via: 'get'
  match '/store/past_orders', to: 'store_orders#past_orders', via: 'get'

end

app/controllers/password_recovery_controller.rb
class PasswordRecoveryController < ApplicationController

  def new
  end

  def create
  	@user = User.find_by_email(params[:email])

  	if @user.present? 
    @user.send_password_recovery 
   	redirect_to root_url, :notice => "Email sent with password reset instructions"
  	else
  	render :new, :notice => "This email is not in the system, please try a different email."
  	end
  end

  def edit
  	@user = User.find_by_password_recovery_token!(params[:id])
  end

  def update
  	@user = User.find_by_password_recovery_token!(params[:id])
  	
	  	if @user.password_recovery_sent_at < 2.hours.ago
	  	redirect_to new_password_recovery_path, :alert => "Password reset has expired."
	  	
	  	elsif @user.update_attributes(user_parameters)
	  	redirect_to root_url, :notice => "Password has been reset!"

	  	else render :edit, :notice => "Please try again."
 		
 		end
 end

def user_parameters
      params.require(:user).permit(:name, :zip, :email, :password,
                           :password_confirmation)
end

end

app/helpers/password_recovery_helper.rb
module PasswordRecoveryHelper
end

app/views/password_recovery/edit.html.erb
<h1>Reset Password</h1>

<%= bootstrap_form_for(@user, url: password_recovery_path(params[:id]), method: :put) do |f| %>
  <%= f.password_field :password, label: "new password" %>

  <%= f.password_field :password_confirmation, label: "new password confirmation" %>
 <div class="buffer"></div>
  <%= f.submit "update password", class: "btn btn-large btn-primary", id: "button" %>
<% end %>

app/views/password_recovery/new.html.erb
<% provide(:title, 'password recovery') %>

<h1 class="text-center"> password recovery </h1>

<div class="row">
  <div class="col-lg-3"></div>
  <div class="col-lg-6">
    <%= bootstrap_form_tag url: "/password_recovery", method: :post do |f| %>

      <%= f.email_field :email, label: "email" %>

      <%= f.submit "submit email", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>