config/routes.rb
OrderApp::Application.routes.draw do
  
  get "order_tickets/new"
  get "order_tickets/create"
  get "order_tickets/index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :stores, only: [:edit, :update, :show] 
  resources :users, except: [:new, :show, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: :create
  resources :store_sessions, only: :create
  resources :meal_limits, only: [:create, :destroy]
  resources :orders, only: [:new, :create, :show]
  resources :password_recovery
  
  root 'static_pages#home'
  
  match '/signup',  to: 'users#new',  via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/store/signin', to: 'store_sessions#new', via: 'get'
  match '/store/signout', to: 'store_sessions#destroy', via: 'delete'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/view_stores', to: 'static_pages#stores_index', via: 'get'
  match '/close_stores', to: 'static_pages#close_store_list', via: 'get'

  match '/store/meal_index', to: 'meal_limits#index', via: 'get'

  match '/past_meals', to: 'meals#index', via: 'get'
  match '/meal/:id', to: 'meals#show', via: 'get', as: 'meal'
  match '/order_history/:id', to: 'meals#order_history', via: 'get', as: 'order_history'

  match '/store/meal/:id', to: 'meal_limits#show', via: 'get', as: 'select_meal'

  match '/store/current_orders', to: 'store_orders#todays_orders', via: 'get'
  match '/store/ready_for_pickup', to: 'store_orders#ready_for_pickup', via: 'patch'
  match '/store/pickup_list', to: 'store_orders#pickup_list', via: 'get'
  match '/store/past_orders', to: 'store_orders#past_orders', via: 'get'

end

app/controllers/store_orders_controller.rb
class StoreOrdersController < ApplicationController
attr_accessor :active

def todays_orders
	@meals_active = Meal.active
    @meal_active = @meals_active.first
   	if @meal_active.present?
    @todays_orders = Order.where(meal_id: @meal_active.id, store_id: current_store.id)
    @not_ready_for_pickup = @todays_orders.where('orders.ready_for_pickup = ?', false)
    @ready_for_pickup = @todays_orders.where('orders.ready_for_pickup = ?', true)
	end
end

def ready_for_pickup
	@order = Order.find_by_id(params[:format])
	@user = User.find_by_id(@order.user_id)
	@meal = Meal.find_by_id(@order.meal_id)
	@store = Store.find_by_id(@order.store_id)

	@order.update_attribute :ready_for_pickup, order_params[:ready_for_pickup]

	redirect_to store_current_orders_path

  OrderReady.order_ready_email(@user).deliver
end

def pickup_list
	@meals_active = Meal.active
    @meal_active = @meals_active.first
   	if @meal_active.present?
    @todays_orders = Order.where(meal_id: @meal_active.id, store_id: current_store.id)
    @order_option = @meal_active.order_options.first
    @ingredients = @order_option.ingredients
	end
end

def past_orders
	if params[:search_email]
	@customer = User.find_by_email(params[:search_email])
    @all_past_orders = Order.where(store_id: current_store.id, user_id: @customer.id).order("created_at DESC")
  	elsif params[:search_name]
    @customer = User.find_by_name(params[:search_name])
    @all_past_orders = Order.where(store_id: current_store.id, user_id: @customer.id).order("created_at DESC")
  	else
    @all_past_orders = Order.where(store_id: current_store.id).order("created_at DESC")
	end
end

private

def order_params
        params.require(:order).permit(:user_id, :meal_id, :order_option_id, :stripeToken, :store_id, :ready_for_pickup)
end

end

app/helpers/store_orders_helper.rb
module StoreOrdersHelper
end

app/views/store_orders/past_orders.html.erb
<% provide(:title, "past orders") %>

<h1>past orders</h1>

<% if @all_past_orders.blank? %>

<h3> you have no past orders </h3>

<% else %>

<%= bootstrap_form_tag url: '/store/past_orders', :method => "get" do %>
  <%= text_field_tag :search_email, params[:search_email], placeholder: "search by customer email" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

</br>

<%= bootstrap_form_tag url: '/store/past_orders', :method => "get" do %>
  <%= text_field_tag :search_name, params[:search_name], placeholder: "search by customer name" %>
  <%= submit_tag "Search", :name => nil %>
<% end %>

<div class="row">
	<div id="past_orders_list" class="col-xs-12">
		<h4> all past orders </h4>
		<div class="buffer"></div>
		<table style="width:100%">
			<tr>
				<th>order number</th>
				<th>meal name</th>
				<th>date created </th>
				<th>customer name</th>
				<th>customer email</th>
			</tr>
		<% @all_past_orders.each do |order| %>
			<tr>
				<td><%= link_to "#{order.id}", order_path(order.id) %></td>
				<td><%= Meal.find_by_id(order.meal_id).name %></td>
				<td><%= formatted_date(order.created_at) %></td>
				<td><%= User.find_by_id(order.user_id).name %></td>
				<td><%= User.find_by_id(order.user_id).email %></td>
			</tr>
		<% end %>
		</table>	
	</div>
</div>

<h3><%= link_to "all past orders", store_past_orders_path %></h3>

<% end %>

app/views/store_orders/pickup_list.html.erb
<% provide(:title, "pickup list") %>

<h1>today's pickup list</h1>

<% if @meal_active.blank? %>

<h3> no orders running today </h3>

<% elsif @meal_active.present? && @todays_orders.blank? %>

<h3> nobody has ordered this meal yet </h3>

<% else %>

<div class="row"></div>

<h4>ingredient pickup</h2>
<div class="row">
	<div class="col-md-10">

		<table class="table">
			<tr>
				<% @ingredients.each do |ingredient| %>
				<th><%= ingredient.name %></th>
				<% end %>
			</tr>

			
			<tr>
			<% @ingredients.each do |this_ingredient| %>
				<td>
				<% sum = 0 %>
				<% @todays_orders.each do |this_order| %>
				<% x = Ingredient.where(order_option_id: this_order.order_option_id, name: this_ingredient.name).first.measurement_quantity %>
				<% sum += x %>
				<% end %>
				<%= sum %> | <%= this_ingredient.measurement_type %>
				</td>
			<% end %>
			</tr>
		</table>

	</div>
</div>
<% end %>

app/views/store_orders/todays_orders.html.erb
<% provide(:title, "current orders") %>

<h1>today's orders</h1>

<% if @meal_active.blank? %>

<h3> no orders running today </h3>

<% elsif @meal_active.present? && @todays_orders.blank? %>

<h3> nobody has ordered this meal yet </h3>

<% else %>

<div class="row"></div>

<h4>incomplete orders </h2>
<div class="row">
	<div class="col-md-10">

		<table class="table">
			<tr>
				<th>order number</th>
				<th>name</th>
				<th>time</th>
				<th>quantity</th>
				<th>ready for pickup?</th>
			</tr>

			<% @not_ready_for_pickup.each do |order| %>

			<tr>

				<td><%= order.id %>
				<td><%= User.find_by_id(order.user_id).name %></td>
				<td><%= order.created_at %></td>
				<td><%= OrderOption.find_by_id(order.order_option_id).size %></td>
				<td>
					<%= bootstrap_form_for(order, url: store_ready_for_pickup_path(order.id)) do |f| %>

      				<%= f.hidden_field :ready_for_pickup, value: true %>
     
      				<%= f.submit "send email", class: "btn btn-large btn-primary", id: "button" %>
					<% end %> 
				</td>

			</tr>

			<% end %>
		</table>

	</div>
</div>

<h4>made orders </h2>
<div class="row">
	<div class="col-md-10">

		<table class="table">
			<tr>
				<th>order number</th>
				<th>name</th>
				<th>time</th>
				<th>quantity</th>
				<th>ready for pickup?</th>
			</tr>

			<% @ready_for_pickup.each do |order| %>

			<tr>
				<td><%= order.id %>
				<td><%= User.find_by_id(order.user_id).name %></td>
				<td><%= order.created_at %></td>
				<td><%= OrderOption.find_by_id(order.order_option_id).size %></td>
				<td>yes</td>
			</tr>

			<% end %>
		</table>

	</div>
</div>

<%= link_to "see pickup list", store_pickup_list_path, class: "btn btn-large btn-primary" %>

<% end %>