config/routes.rb
OrderApp::Application.routes.draw do
  
  get "order_tickets/new"
  get "order_tickets/create"
  get "order_tickets/index"
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  resources :stores, only: [:edit, :update, :show] 
  resources :users, except: [:new, :show, :index] 
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: :create
  resources :store_sessions, only: :create
  resources :meal_limits, only: [:create, :destroy]
  resources :orders, only: [:new, :create, :show]
  resources :password_recovery
  
  root 'static_pages#home'
  
  match '/signup',  to: 'users#new',  via: 'get'
  match '/signin',  to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  match '/store/signin', to: 'store_sessions#new', via: 'get'
  match '/store/signout', to: 'store_sessions#destroy', via: 'delete'

  match '/about', to: 'static_pages#about', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/view_stores', to: 'static_pages#stores_index', via: 'get'
  match '/close_stores', to: 'static_pages#close_store_list', via: 'get'

  match '/store/meal_index', to: 'meal_limits#index', via: 'get'

  match '/past_meals', to: 'meals#index', via: 'get'
  match '/meal/:id', to: 'meals#show', via: 'get', as: 'meal'
  match '/order_history/:id', to: 'meals#order_history', via: 'get', as: 'order_history'

  match '/store/meal/:id', to: 'meal_limits#show', via: 'get', as: 'select_meal'

  match '/store/current_orders', to: 'store_orders#todays_orders', via: 'get'
  match '/store/ready_for_pickup', to: 'store_orders#ready_for_pickup', via: 'patch'
  match '/store/pickup_list', to: 'store_orders#pickup_list', via: 'get'
  match '/store/past_orders', to: 'store_orders#past_orders', via: 'get'

end

app/models/meal_limit.rb
class MealLimit < ActiveRecord::Base
	belongs_to :meal
	belongs_to :store
	validates :store_id, presence: true
	validates :meal_id, presence: true
	validates :availability, presence: true
	validates :current_orders, presence: true

	scope :meal_available, lambda { where("availability > current_orders") }
	scope :meal_not_available, lambda { where("availability <= current_orders") }
end

app/controllers/meal_limits_controller.rb
class MealLimitsController < ApplicationController
  before_action :signed_in_store, only: [:update, :create]

  attr_accessor :editable, :active, :past

  def index
  	@editable_meals = Meal.editable.order('date asc')
    @id = current_store.id
    @meal_limit_set = @editable_meals.joins(:meal_limits).where('meal_limits.store_id = ?', @id)
    @meal_limit_not_set = @editable_meals.where.not(id: @meal_limit_set)
  end

  def show
  	@meal = Meal.find(params[:id])
  end
 
  def create
    @editable_meals = Meal.editable.order('date asc')
    @id = current_store.id
    @meal_limit_set = @editable_meals.joins(:meal_limits).where('meal_limits.store_id = ?', @id)
    @meal_limit_not_set = @editable_meals.where.not(id: @meal_limit_set)
    current_store.meal_limits.create!(meal_limit_params)
    respond_to do |format|
      format.html { redirect_to store_meal_index_path }
      format.js
    end
  end

  def destroy
    @meal_limit = MealLimit.find(params[:id])
    current_store.meal_limits.destroy(@meal_limit)
    @editable_meals = Meal.editable.order('date asc')
    @id = current_store.id
    @meal_limit_set = @editable_meals.joins(:meal_limits).where('meal_limits.store_id = ?', @id)
    @meal_limit_not_set = @editable_meals.where.not(id: @meal_limit_set)
    respond_to do |format|
      format.html { redirect_to store_meal_index_path }
      format.js
    end
  end

    private

    def meal_limit_params
      params.require(:meal_limit).permit(:store_id, :meal_id, :availability,
                           :current_orders)
    end

 end

app/helpers/meal_limits_helper.rb
module MealLimitsHelper
end

app/views/meal_limits/_set_meals.html.erb
<h1>set meals</h1>
<% if @meal_limit_set.empty? %>
	<h3>no meals set<h3>
<% else %>
	<% @meal_limit_set.each do |meal| %> 
		<p><%= meal.name %> <%= formatted_date(meal.date) %> <%= bootstrap_form_for(current_store.meal_limits.find_by(meal_id: meal.id),
             html: { method: :delete }, remote: true) do |f| %>
  		<%= f.submit "Cancel", class: "btn btn-small" %></p>
		<% end %>
	<% end %>
<% end %>

app/views/meal_limits/_show.html.erb
<div class="col-xs-2"></div>
	<div class="col-xs-8 modal-dialog">
		<div class="modal-content">
		<h1><%=@meal.name%></h1>

		<%= bootstrap_form_for(current_store.meal_limits.build(meal_id: @meal.id), remote: true) do |f| %> 
		<div><%= f.hidden_field :meal_id %></div>

		<p><%= f.label :availability, "units available to sell (small = 2, medium = 4, large = 6)" %></p>
		<p><%= f.select :availability, [50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150] %></p>

		<p><%= f.submit "set order params", class: "btn btn-lg btn-success"%></p>
		<% end %>   
		</div>
	</div>
<div class="col-xs-2"></div>

app/views/meal_limits/_unset_meals.html.erb
<h1>unset meals</h1>
	<% if @meal_limit_not_set.empty? %>
		<h3>no meals to set<h3>
	<%else%>
		<% @meal_limit_not_set.each do |meal| %>
		<div class="row">
			<h3><%= link_to meal.name, select_meal_path(meal), data: {:toggle => "modal", :target => "#show-this-meal", :remote => true} %> <%= formatted_date(meal.date)%></h3>
		</div>
	<% end %>
<%end%>

app/views/meal_limits/create.js.erb
$("#show-this-meal").modal('hide');
$("#set_meals").html("<%= escape_javascript(render('meal_limits/set_meals', locals: { meal_limit_set: @meal_limit_set } )) %>");
$("#unset_meals").html("<%= escape_javascript(render('meal_limits/unset_meals', locals: { meal_limit_not_set: @meal_limit_not_set })) %>");

app/views/meal_limits/destroy.js.erb
$("#set_meals").html("<%= escape_javascript(render('meal_limits/set_meals', locals: { meal_limit_set: @meal_limit_set } )) %>");
$("#unset_meals").html("<%= escape_javascript(render('meal_limits/unset_meals', locals: { meal_limit_not_set: @meal_limit_not_set })) %>");

app/views/meal_limits/index.html.erb
<% provide(:title, "set meals") %>


<div class="row">
	<div class="col-sm-6" id="set_meals">
	<%= render "meal_limits/set_meals"%>
	</div>

	<div class="col-sm-6" id="unset_meals">
	<%= render "meal_limits/unset_meals"%>
	</div>
</div>

<div id="show-this-meal" class="modal fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/meal_limits/show.html.erb
<div class="col-xs-12">
	<%= render "meal_limits/show" %>
</div>

app/views/meal_limits/show.js.erb
$("#show-this-meal").html('<%= j render("/meal_limits/show") %>');